#!/usr/bin/env bash

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

alias activestreet=$'ssh stadgent.prod "echo \$(cat \$(grep /etc/apache2/sites-enabled/stadgent_* -e \'ServerAlias stad.gent\' | cut -d\':\' -f1) | grep -oP \'DocumentRoot\s*/\S+\' | cut -d\' \' -f2)"'

