#!/usr/bin/env bash

#
# Setup bash completions for different tools.
# Note that .bash/functions must be sourced before this file because we use
# ssh_load_autocomplete here.
#
# Tip:
# If an alias was defined for a command, completions for that command will not
# work with the defined alias.
# But completion can be configured for that alias, for example:
# Supposing `alias g=git` one can do:
#
#   complete -o default -o nospace -F _git g
#

source /etc/bash_completion.d/git-prompt

